server:
  port: 8086

spring:
  application:
    name: products-service
  cloud:
    kubernetes: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'


---
spring:
  profiles: localhost-docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/